dist: trusty
sudo: required
language:
  - generic

env:
  global:
    - HOME=/home/travis

before_script:
  - cd /tmp
  - git clone https://github.com/ryuichiueda/ros_setup_scripts_Ubuntu14.04_server.git
  - cd ./ros_setup_scripts_Ubuntu14.04_server
  - bash ./step0.bash
  - bash ./step1.bash
  - 
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws/src
  - source /opt/ros/indigo/setup.bash
  - catkin_init_workspace
  - cd ~/catkin_ws
  - catkin_make

script:
  - cd ~/catkin_ws/src/
  - sudo apt-get install ros-indigo-desktop-full
  - sudo apt-get install ros-indigo-gazebo-ros-control ros-indigo-ros-controllers
  - git clone https://github.com/ryuichiueda/raspimouse_ros.git
  - rsync -av /home/travis/build/*/raspimouse_sim ~/catkin_ws/src/raspimouse_sim/
  - source /opt/ros/indigo/setup.bash
  - source ~/catkin_ws/devel/setup.bash
  - cd ~/catkin_ws
  - catkin_make
